version: "3.1"
services:
  app:
    container_name: biblioteca-api
    image: biblioteca-api
    build: ./
    ports:
      - "8080:8081"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
networks:
  biblioteca-network:
    driver: bridge
